// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldnrvhpehdjlixiawbbg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkbnJ2aHBlaGRqbGl4aWF3YmJnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI3NDc2NTcsImV4cCI6MjA1ODMyMzY1N30.58DAyVW53Ff3DJRwHA6DxESVWfxlSC92aoJ1NBdVkPc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);